name: Run Unit Test via Pytest  
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]
    env:
      TBT_DB_URI: 'sqlite://'
      TBT_BASE_URL: 'missing'
      TBT_EMAIL_ADDRESS: 'missing'
      TBT_EMAIL_PASSWORD: 'missing'
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f .requirements ]; then pip install -r .requirements; fi  
      - name: Lint with Ruff  
        run: |  
          pip install ruff  
          ruff --format=github --target-version=py310 .  
        continue-on-error: true  
      - name: Test with pytest  
        run: |  
          coverage run -m pytest  -v -s --junit-xml=test-results.xml
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: 
            rest-results.xml
